/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormCurrency;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author fadly
 */
public class CurrencyConverter extends javax.swing.JFrame {
    
    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = (int) screenSize.getWidth();
        int screenHeight = (int) screenSize.getHeight();
        
        // Mendapatkan ukuran frame
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        
        // Mengatur posisi frame ke tengah layar
        setLocation((screenWidth - frameWidth) / 2, (screenHeight - frameHeight) / 2);
        
        // Mengatur agar frame tidak dapat diubah ukurannya
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelJudul = new javax.swing.JLabel();
        input = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        jTxtInput = new javax.swing.JTextField();
        jComFrom = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComTo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        calculateResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabelJudul.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelJudul.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJudul.setText("Currency Converter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        input.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        input.setForeground(new java.awt.Color(255, 255, 255));
        input.setText("INPUT");

        from.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("FROM");

        jTxtInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtInputActionPerformed(evt);
            }
        });

        jComFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "IDR", "USD", "EURO" }));
        jComFrom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComFrom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComFromActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TO");

        jComTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "IDR", "USD", "EURO" }));
        jComTo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComToActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESULT");

        calculateResult.setEditable(false);
        calculateResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculateResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calculateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jComFrom, 0, 460, Short.MAX_VALUE)
                            .addComponent(from)
                            .addComponent(input)
                            .addComponent(jTxtInput)
                            .addComponent(jComTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calculateResult)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(from)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComTo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculateResult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );

        jComFrom.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtInputActionPerformed
        String str = jTxtInput.getText().trim();
        if (str.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Input cannot be empty. Please enter a valid number.");
        } else {
            try {
                float angka = Float.parseFloat(str);
                String kurs1 = jComFrom.getSelectedItem().toString();
                String kurs2 = jComTo.getSelectedItem().toString();
                String result = "";

                if (kurs1.equalsIgnoreCase("IDR")) {
                    if (kurs2.equalsIgnoreCase("USD")) {
                        result = String.format("%.2f $", angka / 15670.0);
                    } else if (kurs2.equalsIgnoreCase("EURO")) {
                        result = String.format("%.2f €", angka / 16288.0);
                    } else if (kurs2.equalsIgnoreCase("IDR")) {
                        result = "RP. " + (int)angka;
                    }
                } else if (kurs1.equalsIgnoreCase("USD")) {
                    if (kurs2.equalsIgnoreCase("IDR")) {
                        result = String.format("RP. %.2f", angka * 15670.0);
                    } else if (kurs2.equalsIgnoreCase("EURO")) {
                        result = String.format("%.2f €", angka / 1.04);
                    } else if (kurs2.equalsIgnoreCase("USD")) {
                        result = String.format("%.2f $", angka);
                    }
                } else if (kurs1.equalsIgnoreCase("EURO")) {
                    if (kurs2.equalsIgnoreCase("IDR")) {
                        result = String.format("RP. %.2f", angka * 16288.0);
                    } else if (kurs2.equalsIgnoreCase("USD")) {
                        result = String.format("%.2f $", angka * 1.04);
                    } else if (kurs2.equalsIgnoreCase("EURO")) {
                        result = String.format("%.2f €", angka);
                    }
                }

                calculateResult.setText(result);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.");
            }
        }
    }//GEN-LAST:event_jTxtInputActionPerformed

    private void jComFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComFromActionPerformed
        
    }//GEN-LAST:event_jComFromActionPerformed

    private void jComToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComToActionPerformed
       
    }//GEN-LAST:event_jComToActionPerformed

    private void calculateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateResultActionPerformed
        
    }//GEN-LAST:event_calculateResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calculateResult;
    private javax.swing.JLabel from;
    private javax.swing.JLabel input;
    private javax.swing.JComboBox<String> jComFrom;
    private javax.swing.JComboBox<String> jComTo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtInput;
    // End of variables declaration//GEN-END:variables

}
